export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';

export const GET_CURRENT_PRODUCT = 'GET_CURRENT_PRODUCT';
export const GET_CURRENT_PRODUCT_ERROR = 'GET_CURRENT_PRODUCT_ERROR';

export const UPDATE_CURRENT_PRODUCT = 'UPDATE_CURRENT_PRODUCT';
export const UPDATE_CURRENT_PRODUCT_ERROR = 'UPDATE_CURRENT_PRODUCT_ERROR';
